-- Table: payments
-- Stores monthly payment records for each unit

create table public.payments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unit_text text not null,
  month_name text not null,
  year_num integer not null,
  amount numeric default 0,
  due numeric default 0,
  paid_date text,
  
  -- Ensure one record per unit per month per year
  constraint payments_unit_month_year_key unique (unit_text, month_name, year_num)
);

-- Table: units_info
-- Stores occupancy status and notes for each unit (per year)

create table public.units_info (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unit_text text not null,
  year_num integer not null,
  is_occupied boolean default true,
  note text,

  -- Ensure one record per unit per year
  constraint units_info_unit_year_key unique (unit_text, year_num)
);

-- RLS Policies (Row Level Security)
-- For this app, we are allowing public access via the Anon Key.
-- In a production app with real auth, you would restrict this.

alter table public.payments enable row level security;
alter table public.units_info enable row level security;

-- Policies for payments
create policy "Enable read access for all users" on public.payments for select using (true);
create policy "Enable insert access for all users" on public.payments for insert with check (true);
create policy "Enable update access for all users" on public.payments for update using (true);

-- Policies for units_info
create policy "Enable read access for all users" on public.units_info for select using (true);
create policy "Enable insert access for all users" on public.units_info for insert with check (true);
create policy "Enable update access for all users" on public.units_info for update using (true);
