export const FLAT_OWNERS = [
  { flat: '2A', name: 'MATIN', account: '41371285' },
  { flat: '2B', name: 'HANIF', account: '41371286' },
  { flat: '2C', name: 'MINA', account: '41371287' },
  { flat: '3A', name: 'JILLUR', account: '41371298' },
  { flat: '3B', name: 'KAIYUM', account: '41371308' },
  { flat: '3C', name: 'FARUK', account: '41371291' },
  { flat: '4A', name: 'SAIDUR', account: '41371310' },
  { flat: '4B', name: 'IBRAHIM', account: '41371303' },
  { flat: '4C', name: 'AYUB', account: '41371296' },
  { flat: '5A', name: 'MOJAMMEL', account: '41371302' },
  { flat: '5B', name: 'NESAR', account: '41371295' },
  { flat: '5C', name: 'JUWEL', account: '41371309' },
  { flat: '6A', name: 'NESAR', account: '41371299' },
  { flat: '6B', name: 'SHAHIN', account: '41371305' },
  { flat: '6C', name: 'SHAHIDULLAH', account: '41371292' },
  { flat: '7A', name: 'AZAD', account: '41371294' },
  { flat: '7B', name: 'MOROL', account: '41371293' },
  { flat: '7C', name: 'NAZRUL', account: '41371284' },
  { flat: '8A', name: 'ATIQ', account: '41371306' },
  { flat: '8B', name: 'MOSTOFA', account: '41371304' },
  { flat: '8C', name: 'FIROZ', account: '41371301' },
  { flat: '9A', name: 'KAIYUM', account: '41371307' },
  { flat: '9B', name: 'AZHAR', account: '41371297' },
  { flat: '9C', name: 'SAYED', account: '41371300' },
  { flat: '10A', name: 'HAKIM', account: '41371288' },
  { flat: '10B', name: 'MOTIUR', account: '41371289' },
  { flat: '10C', name: 'ASHRAF', account: '41371290' },
  { flat: 'MAIN', name: 'NAZRUL', account: '41371283' },
];

export const TRANSLATIONS = {
  bn: {
    months: [
      'জানুয়ারি', 'ফেব্রুয়ারি', 'মার্চ', 'এপ্রিল', 'মে', 'জুন',
      'জুলাই', 'আগস্ট', 'সেপ্টেম্বর', 'অক্টোবর', 'নভেম্বর', 'ডিসেম্বর'
    ],
    paid: 'পরিশোধিত',
    due: 'বকেয়া',
    upcoming: 'আসন্ন',
    amount: 'টাকা',
    total: 'মোট',
    back: 'পিছনে',
    editInfo: 'তথ্য এডিট করতে ক্লিক করুন',
    occupancy: 'বসবাস',
    occupied: 'বসবাসরত',
    vacant: 'খালি',
    totalAmount: 'মোট টাকা',
    totalDue: 'মোট বকেয়া',
    paymentStatus: 'পেমেন্ট স্ট্যাটাস',
    month: 'মাস',
    monthDate: 'মাস ও তারিখ',
    serviceCharge: 'সার্ভিস চার্জ',
    demo: 'ডেমো মোড',
    adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    allUnitsCalc: 'সকল ইউনিটের হিসাব',
    financialYear: 'অর্থবছর',
    unit: 'ইউনিট',
    totalCollected: 'মোট আদায়',
    searchUnit: 'ইউনিট খুঁজুন...',
    flatType: 'ফ্ল্যাট টাইপ',
    all: 'সব',
    details: 'বিস্তারিত দেখতে ক্লিক করুন',
    adminLogin: 'অ্যাডমিন লগইন',
    loginPrompt: 'পিন কোড দিন',
    loginBtn: 'লগইন',
    saveFail: 'সেভ করতে ব্যর্থ হয়েছে',
    loginError: 'পিন ভুল হয়েছে',
    saveSuccess: 'সফলভাবে সেভ হয়েছে',
    loading: 'লোড হচ্ছে...',
    financialStatus: 'আর্থিক অবস্থা',
    collected: 'আদায়কৃত',
  },
  en: {
    months: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ],
    paid: 'Paid',
    due: 'Due',
    upcoming: 'Upcoming',
    amount: 'Amount',
    total: 'Total',
    back: 'Back',
    editInfo: 'Click to edit info',
    occupancy: 'Occupancy',
    occupied: 'Occupied',
    vacant: 'Vacant',
    totalAmount: 'Total Amount',
    totalDue: 'Total Due',
    paymentStatus: 'Payment Status',
    month: 'Month',
    monthDate: 'Month & Date',
    serviceCharge: 'Service Charge',
    demo: 'Demo Mode',
    adminDashboard: 'Admin Dashboard',
    allUnitsCalc: 'All Units Calculation',
    financialYear: 'Financial Year',
    unit: 'Unit',
    totalCollected: 'Total Collected',
    searchUnit: 'Search unit...',
    flatType: 'Flat Type',
    all: 'All',
    details: 'Click for details',
    adminLogin: 'Admin Login',
    loginPrompt: 'Enter PIN',
    loginBtn: 'Login',
    saveFail: 'Failed to save',
    loginError: 'Incorrect PIN',
    saveSuccess: 'Saved successfully',
    loading: 'Loading...',
    financialStatus: 'Financial Status',
    collected: 'Collected',
  }
};
