export const FLAT_OWNERS = [
  { flat: '2A', name: 'জনাব আব্দুল হাই' },
  { flat: '2B', name: 'জনাব রফিকুল ইসলাম' },
  { flat: '2C', name: 'জনাব মো: শাহজাহান' },
  { flat: '3A', name: 'জনাব মো: হারুন' },
  { flat: '3B', name: 'জনাব মো: ইউসুফ' },
  { flat: '3C', name: 'জনাব মো: ইসমাইল' },
  { flat: '4A', name: 'জনাব মো: ইব্রাহিম' },
  { flat: '4B', name: 'জনাব মো: ইসহাক' },
  { flat: '4C', name: 'জনাব মো: ইয়াকুব' },
  { flat: '5A', name: 'জনাব মো: ইউনুস' },
  { flat: '5B', name: 'জনাব মো: আইয়ুব' },
  { flat: '5C', name: 'জনাব মো: শোয়াইব' },
  { flat: '6A', name: 'জনাব মো: মুসা' },
  { flat: '6B', name: 'জনাব মো: হারুন' },
  { flat: '6C', name: 'জনাব মো: দাউদ' },
  { flat: '7A', name: 'জনাব মো: সুলায়মান' },
  { flat: '7B', name: 'জনাব মো: জাকারিয়া' },
  { flat: '7C', name: 'জনাব মো: ইয়াহিয়া' },
  { flat: '8A', name: 'জনাব মো: ঈসা' },
  { flat: '8B', name: 'জনাব মো: মুহাম্মদ' },
  { flat: '8C', name: 'জনাব মো: আবু বকর' },
  { flat: '9A', name: 'জনাব মো: ওমর' },
  { flat: '9B', name: 'জনাব মো: ওসমান' },
  { flat: '9C', name: 'জনাব মো: আলী' },
  { flat: '10A', name: 'জনাব মো: হামজা' },
  { flat: '10B', name: 'জনাব মো: আব্বাস' },
  { flat: '10C', name: 'জনাব মো: জাফর' },
];

export const TRANSLATIONS = {
  bn: {
    months: [
      'জানুয়ারি', 'ফেব্রুয়ারি', 'মার্চ', 'এপ্রিল', 'মে', 'জুন',
      'জুলাই', 'আগস্ট', 'সেপ্টেম্বর', 'অক্টোবর', 'নভেম্বর', 'ডিসেম্বর'
    ],
    paid: 'পরিশোধিত',
    due: 'বকেয়া',
    upcoming: 'আসন্ন',
    amount: 'টাকা',
    total: 'মোট',
    back: 'পিছনে',
    editInfo: 'তথ্য এডিট করতে ক্লিক করুন',
    occupancy: 'বসবাস',
    occupied: 'বসবাসরত',
    vacant: 'খালি',
    totalAmount: 'মোট টাকা',
    totalDue: 'মোট বকেয়া',
    paymentStatus: 'পেমেন্ট স্ট্যাটাস',
    month: 'মাস',
    monthDate: 'মাস ও তারিখ',
    serviceCharge: 'সার্ভিস চার্জ',
    demo: 'ডেমো মোড',
    adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    allUnitsCalc: 'সকল ইউনিটের হিসাব',
    financialYear: 'অর্থবছর',
    unit: 'ইউনিট',
    totalCollected: 'মোট আদায়',
    searchUnit: 'ইউনিট খুঁজুন...',
    flatType: 'ফ্ল্যাট টাইপ',
    all: 'সব',
    details: 'বিস্তারিত দেখতে ক্লিক করুন',
    adminLogin: 'অ্যাডমিন লগইন',
    loginPrompt: 'পিন কোড দিন',
    loginBtn: 'লগইন',
    saveFail: 'সেভ করতে ব্যর্থ হয়েছে',
    loginError: 'পিন ভুল হয়েছে',
    saveSuccess: 'সফলভাবে সেভ হয়েছে',
    loading: 'লোড হচ্ছে...',
    financialStatus: 'আর্থিক অবস্থা',
    collected: 'আদায়কৃত',
  },
  en: {
    months: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ],
    paid: 'Paid',
    due: 'Due',
    upcoming: 'Upcoming',
    amount: 'Amount',
    total: 'Total',
    back: 'Back',
    editInfo: 'Click to edit info',
    occupancy: 'Occupancy',
    occupied: 'Occupied',
    vacant: 'Vacant',
    totalAmount: 'Total Amount',
    totalDue: 'Total Due',
    paymentStatus: 'Payment Status',
    month: 'Month',
    monthDate: 'Month & Date',
    serviceCharge: 'Service Charge',
    demo: 'Demo Mode',
    adminDashboard: 'Admin Dashboard',
    allUnitsCalc: 'All Units Calculation',
    financialYear: 'Financial Year',
    unit: 'Unit',
    totalCollected: 'Total Collected',
    searchUnit: 'Search unit...',
    flatType: 'Flat Type',
    all: 'All',
    details: 'Click for details',
    adminLogin: 'Admin Login',
    loginPrompt: 'Enter PIN',
    loginBtn: 'Login',
    saveFail: 'Failed to save',
    loginError: 'Incorrect PIN',
    saveSuccess: 'Saved successfully',
    loading: 'Loading...',
    financialStatus: 'Financial Status',
    collected: 'Collected',
  }
};
